version: '3.7'

services:
    app:
        container_name: rest-template
        build:
            context: ../
        environment:
            - SERVER_PORT=8080
            - DB_TYPE=postgres
            - DB_HOST=postgresdatabase
            - DB_PORT=5432
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_NAME=rest-template
        depends_on:
            postgresdatabase:
                condition: service_healthy
        ports:
            - 8080:8080

    postgresdatabase:
        image: postgres:latest
        container_name: postgresdatabase
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: rest-template
        ports:
            - 5432:5432
        volumes:
            - ./database/data/postgres:/var/lib/postgresql/data
            - ../scripts/database/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql:ro
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "your_user", "-d", "rest-template"]
            interval: 5s     # Check every 5 seconds
            timeout: 10s      # Timeout after 10 seconds
            retries: 3        # Mark as unhealthy after 3 failed attempts
            start_period: 5s # Wait 5 seconds before starting health checks