version: '3.7'

services:
    app:
        container_name: rest-template
        build:
            context: ../
        environment:
            - SERVER_PORT=8080
            - DB_TYPE=mongodb
            - DB_HOST=mongodatabase
            - DB_PORT=27017
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_NAME=rest-template
        depends_on:
            - mongodatabase
        ports:
            - 8080:8080

    mongodatabase:
        image: mongo:latest
        container_name: mongodatabase
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: rest-template
        ports:
            - 27017:27017
        volumes:
            - ../scripts/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro