version: '3.7'

services:
    app:
        container_name: rest-template
        build:
            context: ../
        environment:
            - SERVER_PORT=8080
            - DB_TYPE=mysql
            - DB_HOST=mysqldatabase
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_NAME=rest-template
        depends_on:
            mysqldatabase:
                condition: service_healthy
        ports:
            - 8080:8080

    mysqldatabase:
        image: mysql:latest
        container_name: mysqldatabase
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: rest-template
        ports:
            - 3306:3306
        volumes:
            - ./database/data/mysql:/var/lib/mysql
            - ../scripts/database/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
            interval: 5s    # How often to perform the check
            timeout: 10s     # Time to wait for the check to respond
            retries: 3       # How many times to try before considering the service unhealthy
            start_period: 5s # Time to wait before starting the health checks after the container starts